runtime: java
env: flex
service: demo-flex-app
handlers:
- url: /.*
  script: this field is required, but ignored
automatic_scaling:
 min_num_instances: 3
 max_num_instances: 8
 cool_down_period_sec: 300 
 cpu_utilization:
  target_utilization: 0.7

